### ISSUE TITLE
Testing Checklist -- HS 1.9.0

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare-jupyterhub#11]
**USU** 
- [ ] Welcome 
- [ ] Raster Processing using TauDEM
- [x] LandLab Landslide Calculations
- [ ] Basic Time Series Analysis - GenericResource
- [ ] Basic Time Series Analysis - TimeSeriesResource
- [ ] RHESSys Modeling

**NCSA** 
- [ ] Welcome 
- [ ] Raster Processing using TauDEM
- [ ] LandLab Landslide Calculations
- [ ] Basic Time Series Analysis - GenericResource
- [ ] Basic Time Series Analysis - TimeSeriesResource
- [ ] RHESSys Modeling
