### ISSUE TITLE
Items for Release 1.2

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare-jupyterhub#62]
Issues to be resolved for Release 1.2 (July 17th)

**bugs**
- [ ] Unexpected HS_RES_ID on welcome page #56
- [ ] Code check on addContentToExistingResource(parent_resource, files) #55
- [ ] Saving notebooks and outputs #21

**features**
- [ ] Add version to JupyterHub interface #52
- [ ] Matplotlib Font warnings #23
- [ ] Add Contact information to every notebook #16
- [ ] RHESSys Notebook Section Headers #15
- [ ] Standardize output #9
- [ ] Increase width of notebook cells by reducing margins #35
- [ ] Request to install R #57
